name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run tests with PostgreSQL
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/testdb
        run: |
          docker run --rm --network=host \
            -e DATABASE_URL=$DATABASE_URL \
            myapp \
            cargo test

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
